"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to true for local development; set DJANGO_DEBUG=false for deployment.
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() in {'1', 'true', 'yes', 'on'}

_hosts = os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    os.getenv('RENDER_EXTERNAL_HOSTNAME', '127.0.0.1,localhost')
)
ALLOWED_HOSTS = [host.strip() for host in _hosts.split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'tracker',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'backend.middleware.PermissionsPolicyMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
_database_url = os.getenv('DATABASE_URL', '').strip()
if _database_url:
    DATABASES = {
        'default': dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    # Local fallback when DATABASE_URL is not set.
    if not DEBUG:
        raise ImproperlyConfigured('DATABASE_URL must be set when DEBUG is false.')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded files (study materials)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS origins allowed to call this backend.
# Configure with DJANGO_CORS_ALLOWED_ORIGINS as a comma-separated list in production.
_cors_origins = os.getenv(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://0.0.0.0:3000,'
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,'
    'http://127.0.0.1:5174,https://ai-teaching-assistant-hk28.vercel.app'
)
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins.split(',') if origin.strip()]

_csrf_trusted = os.getenv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://ai-teaching-assistant-hk28.vercel.app'
)
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_trusted.split(',') if origin.strip()]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# AI safety controls for production deployment.
APT_AI_LLM_ENABLED = os.getenv('APT_AI_LLM_ENABLED', 'true').lower() in {'1', 'true', 'yes', 'on'}
APT_AI_BACKGROUND_ANALYSIS_ENABLED = os.getenv('APT_AI_BACKGROUND_ANALYSIS_ENABLED', 'true').lower() in {'1', 'true', 'yes', 'on'}
APT_AI_LLM_MODEL = os.getenv('APT_AI_LLM_MODEL', 'gemini-2.5-flash')
APT_AI_LLM_MAX_CALLS_PER_MINUTE = int(os.getenv('APT_AI_LLM_MAX_CALLS_PER_MINUTE', '6'))
APT_AI_LLM_COOLDOWN_SECONDS = int(os.getenv('APT_AI_LLM_COOLDOWN_SECONDS', '180'))
APT_AI_LLM_MAX_RETRIES = int(os.getenv('APT_AI_LLM_MAX_RETRIES', '1'))
APT_AI_LLM_BACKOFF_SECONDS = float(os.getenv('APT_AI_LLM_BACKOFF_SECONDS', '1.0'))