# Generated by Django 6.0.2 on 2026-02-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('parent_number', models.CharField(default='', max_length=15)),
                ('class_name', models.CharField(max_length=5)),
            ],
        ),
    ]
