# Generated by Django 6.0.2 on 2026-02-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_testmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmark',
            name='subject',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
