# Generated by Django 6.0.2 on 2026-03-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_teachercredential_assigned_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingtest',
            name='num_questions',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='upcomingtest',
            name='questions_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upcomingtest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingtest',
            name='study_material',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/'),
        ),
        migrations.AlterField(
            model_name='upcomingtest',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('finished', 'Finished')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT_ANSWER', 'Short Answer'), ('TRUE_FALSE', 'True/False')], default='MCQ', max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(default='AI_GEMINI', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tracker.upcomingtest')),
            ],
            options={
                'ordering': ['test', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.FloatField(default=0)),
                ('response_time', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_responses', to='tracker.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='tracker.upcomingtest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='tracker.testquestion')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('student', 'question', 'test')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('percentage', models.FloatField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Expired', 'Expired'), ('InProgress', 'In Progress')], default='InProgress', max_length=20)),
                ('topic_wise_analysis', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('predicted_performance', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='tracker.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tracker.upcomingtest')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('student', 'test')},
            },
        ),
    ]
