# Generated by Django 6.0.2 on 2026-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_upcomingtest_end_time_upcomingtest_num_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtest',
            name='teacher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
