# Generated by Django 6.0.2 on 2026-03-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_upcomingtest_teacher_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
