# Generated by Django 6.0.2 on 2026-03-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_upcomingtest_question_bank'),
    ]

    operations = [
    ]
