# Generated by Django 6.0.2 on 2026-04-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_testattempt_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptual_patterns', models.JSONField(blank=True, default=list)),
                ('behavior_patterns', models.JSONField(blank=True, default=list)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='tracker.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='tracker.upcomingtest')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'test')},
            },
        ),
    ]
